URL_CPNU = "https://consultaprocesos.portalhistorico.ramajudicial.gov.co:448/api/v2/Procesos/Consulta/NumeroRadicacion?numero="
URL_CPNU_SINGLE = "https://consultaprocesos.portalhistorico.ramajudicial.gov.co:448/api/v2/Proceso/"
URL_CPNU_ACTUACIONES = "https://consultaprocesos.portalhistorico.ramajudicial.gov.co:448/api/v2/Proceso/Actuaciones/"
URL_RAMA_JUDICIAL="https://portalhistorico.ramajudicial.gov.co/portal/inicio"
URL_RAMA_JUDICIAL_INICIO="https://portalhistorico.ramajudicial.gov.co"