URL_CPNU = "https://consultaprocesos.ramajudicial.gov.co:448/api/v2/Procesos/Consulta/NumeroRadicacion?numero="
URL_CPNU_SINGLE = "https://consultaprocesos.ramajudicial.gov.co:448/api/v2/Proceso/Detalle/"
URL_CPNU_ACTUACIONES = "https://consultaprocesos.ramajudicial.gov.co:448/api/v2/Proceso/Actuaciones/"
URL_RAMA_JUDICIAL="https://www.ramajudicial.gov.co/portal/inicio"
URL_RAMA_JUDICIAL_INICIO="https://www.ramajudicial.gov.co"